"""Initial migration

Revision ID: 271cd7d32627
Revises:
Create Date: 2026-07-11 15:44:37.711087

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "271cd7d32627"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("work_duration_minutes", sa.Integer(), nullable=False),
        sa.Column("short_break_minutes", sa.Integer(), nullable=False),
        sa.Column("long_break_minutes", sa.Integer(), nullable=False),
        sa.Column("sound_enabled", sa.Boolean(), nullable=False),
        sa.Column("theme", sa.String(length=16), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("updated_at_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "work_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("client_session_id", sa.String(length=64), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("planned_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("actual_duration_seconds", sa.Integer(), nullable=False),
        sa.Column("started_at_utc", sa.DateTime(), nullable=False),
        sa.Column("completed_at_utc", sa.DateTime(), nullable=False),
        sa.Column("created_at_utc", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_session_id"),
        sa.UniqueConstraint(
            "client_session_id", name="uq_work_sessions_client_session_id"
        ),
    )
    with op.batch_alter_table("work_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_work_sessions_completed_at_utc"),
            ["completed_at_utc"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_work_sessions_mode"), ["mode"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_work_sessions_started_at_utc"),
            ["started_at_utc"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("work_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_work_sessions_started_at_utc"))
        batch_op.drop_index(batch_op.f("ix_work_sessions_mode"))
        batch_op.drop_index(batch_op.f("ix_work_sessions_completed_at_utc"))

    op.drop_table("work_sessions")
    op.drop_table("user_settings")
    # ### end Alembic commands ###
